### ISSUE TITLE
add a pin showing FAC HQ, and one other location

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/street-flowers#5]
dependant on #4

**Comment by NataliaLKB** [comment]
Hey! @Neats29 pulled down your pins branch and it looks great! 

Is it ready to merge into master?

**Comment by Neats29** [comment]
yes it's ready to merge, its just the pins.

**Comment by NataliaLKB** [comment]
Okay when you are ready please send a PR!
